version: "3.2"
services:
  javavulny-pg:
    image: postgres
    container_name: javavulny-pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgresql
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql

  javavulny:
    build: .
    image: stackhawk/javavulny:latest
    container_name: javavulny
    ports:
      - "9000:9000"
    links:
      - javavulny-pg
    depends_on:
      - javavulny-pg
